import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import { Header } from './components/header'
import { SettingsSidebar } from './components/settings-sidebar'
import { SideNavigationBar } from './components/side-navigation-bar'
import './globals.css'

const kalpurush = localFont({
  src: './fonts/kalpurush.ttf',
  variable: '--font-kalpurush',
})

const me_quran = localFont({
  src: './fonts/me_quran.ttf',
  variable: '--font-me_quran',
})

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body
        className={`${inter.variable} ${kalpurush.variable} ${me_quran.variable} h-screen overflow-hidden bg-background antialiased`}
      >
        <Header />
        <div className="grid h-full grid-cols-1 gap-6 px-4 pt-4 xl:grid-cols-[100px,1fr] 2xl:grid-cols-[100px,1fr,300px] 2xl:px-10 2xl:pt-10">
          <SideNavigationBar />
          {children}
          <SettingsSidebar />
        </div>
        <div id="modal" />
      </body>
    </html>
  )
}
